# Generated by Django 4.2 on 2023-07-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventacarta', '0003_venta_carta_imagen_usuario_contrasenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idventa',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idCarta',
        ),
        migrations.AddField(
            model_name='carta',
            name='ventas_relacionadas',
            field=models.ManyToManyField(to='ventacarta.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_carta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventacarta.carta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventacarta.usuario'),
        ),
    ]
