# Generated by Django 4.2 on 2023-07-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventacarta', '0004_remove_usuario_idventa_remove_venta_idcarta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='venta_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_venta', to='ventacarta.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_carta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventacarta.carta'),
        ),
    ]
